# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dependencies for hipercow-api
      run: dotnet add hipercow-api package Microsoft.HPC.SDK --version 6.3.8025-beta
    - name: Install dependencies for hipercow-api-unit-tests
      run: dotnet add hipercow-api-unit-tests package Microsoft.HPC.SDK --version 6.3.8025-beta
    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test
    - name: Coverage
      run: dotnet-coverage collect -f xml dotnet test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: mrc-ide/hipercow-api
	file: output.xml
	directory: .
